global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal:
      - 'alertname'

receivers:
- name: 'default-receiver'
  # Placeholder - replace with actual receiver config (e.g., Slack, PagerDuty)
- name: 'critical-alerts'
  # Placeholder - replace with actual receiver config
- name: 'warning-alerts'
  # Placeholder - replace with actual receiver config