apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-engine
  labels:
    app.kubernetes.io/name: analytics-engine
    app.kubernetes.io/component: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-engine
        app.kubernetes.io/component: analytics
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: analytics-engine
        image: footanalytics/analytics-engine:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /startup
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

