apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  labels:
    app.kubernetes.io/name: ml-pipeline
    app.kubernetes.io/component: ml-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-pipeline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-pipeline
        app.kubernetes.io/component: ml-processing
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: ml-pipeline
        image: footanalytics/ml-pipeline:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
