apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: video-ingestion
  labels:
    app.kubernetes.io/name: video-ingestion
    app.kubernetes.io/component: ingestion
spec:
  selector:
    app.kubernetes.io/name: video-ingestion
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-engine
  labels:
    app.kubernetes.io/name: analytics-engine
    app.kubernetes.io/component: analytics
spec:
  selector:
    app.kubernetes.io/name: analytics-engine
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  labels:
    app.kubernetes.io/name: ml-pipeline
    app.kubernetes.io/component: ml-processing
spec:
  selector:
    app.kubernetes.io/name: ml-pipeline
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
