apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-ingestion
  labels:
    app.kubernetes.io/name: video-ingestion
    app.kubernetes.io/component: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: video-ingestion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: video-ingestion
        app.kubernetes.io/component: ingestion
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: video-ingestion
        image: footanalytics/video-ingestion:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
