global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway-perf'
    static_configs:
      - targets: ['api-gateway-perf:4000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'video-ingestion-perf'
    static_configs:
      - targets: ['video-ingestion-perf:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'analytics-engine-perf'
    static_configs:
      - targets: ['analytics-engine-perf:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres-perf'
    static_configs:
      - targets: ['postgres-perf:5432']
    scrape_interval: 10s

  - job_name: 'redis-perf'
    static_configs:
      - targets: ['redis-perf:6379']
    scrape_interval: 10s

  - job_name: 'pulsar-perf'
    static_configs:
      - targets: ['pulsar-perf:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
