# API Gateway Staging Configuration Patch

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        env:
        - name: NODE_ENV
          value: "staging"
        - name: GRAPHQL_PLAYGROUND
          value: "true"
        - name: GRAPHQL_INTROSPECTION
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
        - name: CORS_ORIGIN
          value: "*"
        - name: RATE_LIMIT_MAX
          value: "500"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
