# ML Pipeline Staging Configuration Patch

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        - name: BATCH_SIZE
          value: "8"  # Smaller batch size for staging
        - name: MAX_WORKERS
          value: "2"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            nvidia.com/gpu: 0  # No GPU for staging
          limits:
            memory: "2Gi"
            cpu: "1000m"
