groups:
- name: istio-service-mesh
  rules:
  - alert: HighHTTPErrorRate
    expr: sum(rate(istio_requests_total{response_code=~"5.."}[1m])) / sum(rate(istio_requests_total[1m])) > 0.05
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High HTTP Error Rate ({{ $value }}%)"
      description: "More than 5% of requests are failing in namespace {{ $labels.namespace }}"

  - alert: LatencyIncrease
    expr: histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket[1m])) by (le)) > 1.5
    for: 5m
    labels:
      severity: warning